### ISSUE TITLE
Arr::isAssoc() error on Nova version 2.7.0

### ISSUE THREAD

**Issue by inodesrl** [vyuldashev/nova-permission#100]
After updating nova to version 2.7.0, in the permission resource an error
From the browser inspector:
"message": "Argument 1 passed to Illuminate\\Support\\Arr::isAssoc() must be of the type array, object given, called in /var/www/clients/client2/web25/private/nova/src/Fields/Select.php on line 37",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",

I attach the screenshot
thanks, Marco.
![Cattura](https://user-images.githubusercontent.com/21054404/68773967-b4cec980-062c-11ea-83fb-64c1d1a3c9fc.JPG)

**Comment by ivantorgov** [comment]
I have the same issue :-(

**Comment by MENtechmedia** [comment]
I have made a pull request with a hotfix for this problem. 

To solve it for now, just add toArray() after the pluck() method in the fields() method of the attachToRole.php class.

**Comment by inodesrl** [comment]
thanks !

**Comment by vyuldashev** [comment]
Tagged v2.3.1

**Comment by pipizdos** [comment]
@vyuldashev still getting same error with 2.7.1 nova and 2.4 nova-permission
if i change source to 
```

        $roleClass = app(PermissionRegistrar::class)->getRoleClass();
        $this->options($roleClass::get()->pluck('name', 'name')->toArray());
```
it works, but if i leave it as is with \Closure
```
$this->options(static function () {
            $roleClass = app(PermissionRegistrar::class)->getRoleClass();

            return $roleClass::get()->pluck('name', 'name')->toArray();
        });
```
obviously it passes object to options() and isAssoc fails again

**Comment by pipizdos** [comment]
error log:
```
[2019-11-25 16:21:49] local.ERROR: Argument 1 passed to Illuminate\Support\Arr::isAssoc() must be of the type array, object given, called in /home/vagrant/code/project/nova/src/Fields/BooleanGroup.php on line 32 {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Illuminate\\Support\\Arr::isAssoc() must be of the type array, object given, called in /home/vagrant/code/project/nova/src/Fields/BooleanGroup.php on line 32 at /home/vagrant/code/project/vendor/laravel/framework/src/Illuminate/Support/Arr.php:353)
[stacktrace]
#0 /home/vagrant/code/project/nova/src/Fields/BooleanGroup.php(32): Illuminate\\Support\\Arr::isAssoc(Object(Closure))
#1 /home/vagrant/code/project/vendor/vyuldashev/nova-permission/src/RoleBooleanGroup.php(30): Laravel\\Nova\\Fields\\BooleanGroup->options(Object(Closure))
#2 /home/vagrant/code/project/nova/src/Element.php(46): Vyuldashev\\NovaPermission\\RoleBooleanGroup->__construct('Roles')
#3 /home/vagrant/code/project/app/Nova/User.php(63): Laravel\\Nova\\Element::make('Roles')
#4 /home/vagrant/code/project/nova/src/ResolvesFields.php(393): App\\Nova\\User->fields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#5 /home/vagrant/code/project/nova/src/ResolvesFields.php(244): Laravel\\Nova\\Resource->availableFields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#6 /home/vagrant/code/project/nova/src/ResolvesFields.php(315): Laravel\\Nova\\Resource->resolveFields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#7 /home/vagrant/code/project/nova/src/ResolvesFields.php(328): Laravel\\Nova\\Resource->resolveAvatarField(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#8 /home/vagrant/code/project/nova/src/Fields/BelongsTo.php(316): Laravel\\Nova\\Resource->resolveAvatarUrl(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#9 /home/vagrant/code/project/nova/src/Http/Controllers/AssociatableController.php(33): Laravel\\Nova\\Fields\\BelongsTo->formatAssociatableResource(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), Object(App\\Nova\\User))
#10 [internal function]: Laravel\\Nova\\Http\\Controllers\\AssociatableController->Laravel\\Nova\\Http\\Controllers\\{closure}(Object(App\\Nova\\User), 0)
#11 /home/vagrant/code/project/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#12 /home/vagrant/code/project/nova/src/Http/Controllers/AssociatableController.php(34): Illuminate\\Support\\Collection->map(Object(Closure))
#13 [internal function]: Laravel\\Nova\\Http\\Controllers\\AssociatableController->index(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'user-projects', 'user')
```

**Comment by MENtechmedia** [comment]
Just curious, why do you need a static function as a callback? Try using a normal function as callback.

**Comment by pipizdos** [comment]
@MENtechmedia doesn't matter static or normal, it'll pass \Closure object to Arr::isAssoc

**Comment by pipizdos** [comment]
possible solution is just call closure where it created
(closure())()

**Comment by MENtechmedia** [comment]
yes, I agree. Options expect an array, not a anonymouse function. So this is never gonna work. Indeed calling the function instantly would solve the problem I guess? 

I can make a pull request tomorrow for a fix.

**Comment by pipizdos** [comment]
would be great thanks.

**Comment by n0n0n0n0** [comment]
up

**Comment by alexsaab** [comment]
Same error, up

**Comment by Elllex** [comment]
same error
